- name: Copy FPM Upstart Config
  template: src=fpm-upstart.conf.j2 dest=/etc/init/php{{ phpenv_global }}-fpm.conf
  become: yes
  notify: Update RC

- name: Copy FPM Init Script
  template: src=fpm-init.sh.j2 dest=/etc/init.d/php{{ phpenv_global }}-fpm mode=0755
  become: yes
  notify: Update RC

- name: Delete Default FPM Config
  file: name={{ phpenv_root }}/versions/{{ phpenv_global }}/etc/php-fpm.conf.default state=absent
  notify: Restart FPM

- name: Copy php.ini
  template: src=php.ini.j2 dest={{ phpenv_root }}/versions/{{ phpenv_global }}/etc/php.ini
  notify: Restart FPM

- name: Copy FPM Config
  template: src=fpm.conf.j2 dest={{ phpenv_root }}/versions/{{ phpenv_global }}/etc/php-fpm.conf
  notify: Restart FPM

- name: Create Pool Directory
  file: name={{ phpenv_root }}/versions/{{ phpenv_global }}/etc/pool.d state=directory

- name: Copy FPM Pool Config
  template: src=fpm-pool.conf.j2 dest={{ phpenv_root }}/versions/{{ phpenv_global }}/etc/pool.d/{{ domain }}.conf
  when: domain is defined
  notify: Restart FPM
