---
- name: execute install script
  shell: "PHPENV_ROOT={{ phpenv_root }} ./bin/phpenv-install.sh"
  args:
    chdir: "{{ mktemp.stdout }}"
  ignore_errors: yes

- name: create plugins directory
  file: state=directory path={{ phpenv_root }}/plugins

- name: install plugins
  git: >
    repo={{ item.repo }}
    dest={{ phpenv_root }}/plugins/{{ item.name }}
    version={{ item.version }}
    depth={{ item.depth }}
    accept_hostkey=true
  with_items: phpenv_plugins



